### ISSUE TITLE
Global Sprint 2016 - PLAN

### ISSUE THREAD

**Issue by arlissc** [mozillascience/global-sprint-2016#1]
Here is the link to the planning document for the Global Sprint 2016

https://docs.google.com/a/mozilla.com/document/d/1COL9rNBvVEVVPod3ecAIdE53736ut0xhsOo-ZyxJEb4/edit?usp=sharing

**Comment by andreabedini** [comment]
the link seems to have some issue but copy and pasting the url works for me

**Comment by stephwright** [comment]
I think the link is fixed now

**Comment by acabunoc** [comment]
Migrated to https://github.com/mozillascience/plan/issues/72
