### ISSUE TITLE
openSNP

### ISSUE THREAD

**Issue by acabunoc** [mozillascience/global-sprint-2016#10]
**[ Project Lead ]** @gedankenstuecke
**[ GitHub Repo ]** https://github.com/openSNP/snpr
**[ Track ]** Tools: you are building a tool others can help you build
**[ Level ]** Intermediate
**[ Timezone ]** UTC+2 and UTC+8
### Description

Hello! openSNP.org is a repository to which users can upload their SNP-sets (and exome-VCFs) from 23andme, deCODEme, FamilyTreeDNA, AncestryDNA and IYG-format (for participants of EBI genotyping). On upload, SNPs are annotated using the PLoS and Mendeley-APIs to show users the newest scientific research results on their SNPs. Each SNP is also linked to the relevant page on SNPedia. SNPs are ranked according to how many results could be gathered for SNPedia, PLoS and Mendeley (in that order). Users can send each other private messages as well as comment on SNPs and Phenotypes.

---
## Want to Contribute?

Join us at the [Global Sprint June 2-3](https://www.mozillascience.org/global-sprint-2016). Leave a comment in this issue to let the project lead know you're interested in contributing during #mozsprint 2016!

---
## Note to the Project Lead

Congrats, @gedankenstuecke! This is your official project listing for the [Mozilla Science Global Sprint 2016](https://www.mozillascience.org/global-sprint-2016). Please comment on this issue to confirm your project submission and complete the following:
- [x] Provide a GitHub repository for work and discussion on your project
- [x] Confirm in a comment that at least one person will be available to review and answer questions on this project from 9-5 in their timezone on both June 2 & 3.

**Comment by gedankenstuecke** [comment]
Yep, that should work, Philipp and I have our eyes fixed set on it :)

**Comment by Varix** [comment]
I think I am leaning towards this project... is there a current todo list or repo for it?

**Comment by gedankenstuecke** [comment]
Hey @Varix, thanks for the interest and sorry for the slow reply. I was pretty much out of office this weekend. ☀️  We do have a [repo](https://github.com/openSNP/snpr) where you can find our [Roadmap](https://github.com/openSNP/snpr/blob/master/ROADMAP.md) that contains the stuff that we want to work on in the future. There's also a [guide for new contributors](https://github.com/openSNP/snpr/blob/master/CONTRIBUTING.md) and of course there are always [open issues](https://github.com/openSNP/snpr/issues).

That's a lot to take in at single time, so please feel free to [drop by in our Gitter channel to have a chat with us](https://gitter.im/openSNP/snpr), any time you feel like it. We're based in pretty much every timezone by now, so usually there's someone awake, so replies shouldn't take too long.

**Comment by gedankenstuecke** [comment]
Doing the autumn GH cleanup. I think last year's global sprint is over now 😉
