### ISSUE TITLE
Move non-project issues to /plan

### ISSUE THREAD

**Issue by acabunoc** [mozillascience/global-sprint-2016#16]
Hey @arlissc & @stephwright -- I think it might help users if we move all our planning issues to the /plan repo and keep this as a list of projects. Does that make sense to you? Any objections?

Issues affected: #1, #3, #4 & this issue (#16)

(sorry it's late, I can't sleep 🌙 ⭐)

**Comment by stephwright** [comment]
No objections, though wondering if it would make sense to just label these as planning and keep them here as they relate to the global sprint?  Then folks can filter out issues labeled "planning"

**Comment by acabunoc** [comment]
True, but thinking of ppl new to github I thought that might be more confusing

**Comment by arlissc** [comment]
I'm happy to migrate and close the issues.  I support keeping this repo uncluttered for all points mentioned.

**Comment by stephwright** [comment]
Okie doke!

**Comment by acabunoc** [comment]
Done!
