### ISSUE TITLE
Make a landing page for the global sprint 2016

### ISSUE THREAD

**Issue by acabunoc** [mozillascience/global-sprint-2016#2]

**Comment by acabunoc** [comment]
@auremoser - let me know if want to help here!

**Comment by acabunoc** [comment]
https://www.mozillascience.org/global-sprint-2016

Quick pass ^

**Comment by auremoser** [comment]
I'm sorry abby, i missed this notification. thanks for stepping in. I had thought the landing page would be more about logistics and site locations. Can you embed a map if I give you an iframe? I'm not sure we need an external page if so.

**Comment by acabunoc** [comment]
No worries! Arliss needed a page listing some of our current projects before she her announcement post.

I left off all the map stuff and a lot of extra info for now. There'll be lots of updates over the next few weeks! Also, by the time the spring comes around we should be on our new site

**Comment by auremoser** [comment]
Hey @arlissc + @acabunoc: so I made a little one here, it's a gh-page on the global sprint repo, when participants fill out the venue form, I can add it to the map and table with a custom etherpad we make for them: <http://mozillascience.github.io/global-sprint-2016/> I guess we could also just merge it to what Abby has, just let me know what you want me to do, I'd already started this so it's not too much work lost.

**Comment by acabunoc** [comment]
Hey @auremoser! We should probably use the page on the website since it's crosslinked with all projects (& participants if we add them). 

See events linked on the [phageparser project page](https://mozillascience.org/projects/pathogens):
![screen shot 2016-03-22 at 19 51 49](https://cloud.githubusercontent.com/assets/617994/13971576/96597f38-f067-11e5-8837-f1177664169c.png)


You can look at what we did last year:
http://www.mozillascience.org/global-sprint-2015

I would intentionally leave off any site maps / details until we have actual sites & details to advertise! We'll be remaking this page again as an event on the new site.

**Comment by acabunoc** [comment]
@auremoser sorry you went through all the work to setup a separate page!

**Comment by auremoser** [comment]
O.k. @acabunoc , that's fine. I guess I thought after talking to arliss we were going to have a map with the sites defined and the etherpads, but maybe not, I guess it can just sit there for now. 
No worries, I like making websites.

**Comment by acabunoc** [comment]
@auremoser we can def have those things (some of them are on the 2015 site!), but it should be on the main website for crosslinking / event listing purposes. And we should only add them once we can actually populate things

makes sense?

**Comment by auremoser** [comment]
Oh sorry, I didn't see the 2015 site, I guess i was confused about why I was assigned this then. The other site totally makes sense, feel free to go ahead with that, anyone can delete the gh-pages if you'd rather not have that public.

**Comment by acabunoc** [comment]
Oh sorry, the issue was assigned to me! Flagged you in case you had time on Monday :)

Sorry there was a quick deadline on this one
