### ISSUE TITLE
Grafoscopio: moldable tool for data narratives & visualizations

### ISSUE THREAD

**Issue by acabunoc** [mozillascience/global-sprint-2016#20]
**[ Project Lead ]** Offray
**[ GitHub Repo ]** http://smalltalkhub.com/#!/~Offray/Grafoscopio
**[ Track ]** Tools: you are building a tool others can help you build, Open Educational Resource: you're collaborating on curriculum or other educational resources, Citizen Science: you're looking for participants in your citizen science project, Open Data: you have data others can use and play with during the sprint
**[ Level ]** Beginner

### Description
A moldable, self-contained tool for interactive notebooks, data narratives & visualizations to support/bootstrap emerging practices from citizens, journalist, researchers and/or hackers, designed from a Global South context.

***
## Want to Contribute?
Join us at the [Global Sprint June 2-3](https://www.mozillascience.org/global-sprint-2016). Leave a comment in this issue to let the project lead know you're interested in contributing during #mozsprint 2016!
***

## Note to the Project Lead
Congrats, Offray! This is your official project listing for the [Mozilla Science Global Sprint 2016](https://www.mozillascience.org/global-sprint-2016). To confirm your submission, please complete the following:

- [ ] Provide a GitHub repository for work and discussion on your project
- [ ] Confirm in a comment that at least one person will be available to review and answer questions on this project from 9-5 in their timezone on both June 2 & 3.

#### Do you want to become a featured project? :tada:
Here are some exercises that will help your project be more inviting to new contributors. We hope you'll try to complete some of these as you prepare for #mozsprint.

If you complete *all* the exercises, your project will be eligible to be featured in our [collection of open source science projects](https://mozillascience.org/collaborate)! Once you've finished this list, contact @acabunoc to submit your project for review.

* [ ] [README.md](http://mozillascience.github.io/working-open-workshop/writing_readme/):
* [ ] [LICENSE](http://choosealicense.com/):
* [ ] [CONTRIBUTING.md](http://mozillascience.github.io/working-open-workshop/contributing/):
* [ ] [Roadmap or an Issue Tracker (with tasks to complete)](http://mozillascience.github.io/working-open-workshop/roadmapping/):
* [ ] [Data Reuse Plan](http://mozillascience.github.io/working-open-workshop/data_reuse/) (if applicable):
* [ ] [Code of Conduct](http://mozillascience.github.io/working-open-workshop/code_of_conduct/):
* [ ] [Personas](http://mozillascience.github.io/working-open-workshop/personas_pathways/):

**Comment by offray** [comment]
My project doesn't use GitHub explicitly, but I can provide a Fossil repository for comments, issues, tickets and so on. Will this work or not using github precludes project from further participation? 

Thanks,

Offray

**Comment by acabunoc** [comment]
Hey @offray! Yes, please link your Fossil repo :)

We prefer github for integration (we use the github api to track activity & contributions) & it's required for featured projects right now. But you're welcome to bring your project on a separate platform!

**Comment by offray** [comment]
Thanks @acabunoc. So how can I edit this issue to point check the completed task and point to the external repository?

**Comment by acabunoc** [comment]
Hey @offray! you should be able to update this issue now! Thanks so much - excited to see this project at the sprint 😄
