### ISSUE TITLE
Special Questions for Open Data submissions

### ISSUE THREAD

**Issue by stephwright** [mozillascience/global-sprint-2016#3]
Identify questions needed for open data submissions.
Such as:
Data Stuff
- where is the data stored ? 
    * Is it accessible by everyone?
    * If not, what needs to happen so participants can access?
- in what format is the data?
  * do participants need special and/or non-open software to use the data?
- are there licensing (or other) restrictions on the data for reuse?
- how large is the data file/s?

Brian Bot / ~~Ali Swanson - want to bring data to the sprint~~
- see people come to the sprint to do some analysis, maybe do some data cleaning  
Brian - human data - need to request access (6 days) - can bring him in to do a datahack  
~~Ali - Serengeti - do some analysis~~

**Comment by acabunoc** [comment]
Migrated to https://github.com/mozillascience/plan/issues/71
