### ISSUE TITLE
Update sites.geojson to list all participants

### ISSUE THREAD

**Issue by RaoOfPhysics** [mozillascience/global-sprint-2016#31]
… so no-one feels left out. :)

**Missing**:

- USA:
    - [ ] [Berkeley](https://ti.to/mozilla-science/gs2016-berkeley)
    - [x] [Charlottesville](https://ti.to/mozilla-science/gs2016-charlottesville)
    - [x] [Seattle](https://ti.to/mozilla-science/gs2016-seattle)
    - [x] [St Paul](https://ti.to/mozilla-science/gs2016-st-paul)
- India:
    - [x] [Bangalore](https://ti.to/mozilla-science/gs2016-bangalore)
    - [x] [Barasat](https://ti.to/mozilla-science/gs2016-barasat)
    - [ ] [Chennai](https://ti.to/mozilla-science/gs2016-chennai)
    - [x] [Madurai](https://ti.to/mozilla-science/gs2016-madurai)
- UK:
    - [x] [Edinburgh](https://ti.to/mozilla-science/gs2016-edinburgh)
    - [ ] [Exeter](https://ti.to/mozilla-science/gs2016-exeter)
    - [ ] [Norwich](https://ti.to/mozilla-science/gs2016-norwich-uk)
- […]

**Comment by acabunoc** [comment]
hey, we're not using that geojson anymore! (@auremoser moved us to cartodb 😄 ) will delete

**Comment by RaoOfPhysics** [comment]
Ah! :) Should've waited for your go-ahead before adding them.
