### ISSUE TITLE
Exploratory analysis with Pathway Commons, R Cytoscape.js, and Shiny

### ISSUE THREAD

**Issue by acabunoc** [mozillascience/global-sprint-2016#33]
**[ Project Lead ]** @kdaily
**[ GitHub Repo ]** https://github.com/kdaily/shinyPathway
**[ Track ]** Tools: you are building a tool others can help you build
**[ Level ]** Intermediate
**[ Timezone ]** PDT
### Description

Build a modular R Shiny app to view biological pathways from Pathway Commons with user-provided data about nodes in the network.

---
## Want to Contribute?

Join us at the [Global Sprint June 2-3](https://www.mozillascience.org/global-sprint-2016). Leave a comment in this issue to let the project lead know you're interested in contributing during #mozsprint 2016!

---
## Note to the Project Lead

Congrats, @kdaily! This is your official project listing for the [Mozilla Science Global Sprint 2016](https://www.mozillascience.org/global-sprint-2016). To confirm your submission, please complete the following:
- [x] Provide a GitHub repository for work and discussion on your project
- [x] Confirm in a comment that at least one person will be available to review and answer questions on this project from 9-5 in their timezone on both June 2 & 3.
#### Do you want to become a featured project? :tada:

Here are some exercises that will help your project be more inviting to new contributors. We hope you'll try to complete some of these as you prepare for #mozsprint.

If you complete _all_ the exercises, your project will be eligible to be featured in our [collection of open source science projects](https://mozillascience.org/collaborate)! Once you've finished this list, contact @acabunoc to submit your project for review.
- [x] [README.md](http://mozillascience.github.io/working-open-workshop/writing_readme/):
- [x] [LICENSE](http://choosealicense.com/):
- [x] [CONTRIBUTING.md](http://mozillascience.github.io/working-open-workshop/contributing/):
- [x] [Roadmap or an Issue Tracker (with tasks to complete)](http://mozillascience.github.io/working-open-workshop/roadmapping/):
- [ ] [Data Reuse Plan](http://mozillascience.github.io/working-open-workshop/data_reuse/) (if applicable):
- [x] [Code of Conduct](http://mozillascience.github.io/working-open-workshop/code_of_conduct/):
- [ ] [Personas](http://mozillascience.github.io/working-open-workshop/personas_pathways/):

**Comment by kdaily** [comment]
Github repo: https://github.com/kdaily/shinyPathway

I'll be available from 9-5 in my local timezone on both June 2 and 3.
