### ISSUE TITLE
Must I close the project? I will not be available on June 2 and 3.

### ISSUE THREAD

**Issue by offray** [mozillascience/global-sprint-2016#37]
Hi,

I'm sorry to inform that on June first I will be flying back to my country, and I need to take care of some logistics after I land, so I would be unavailable the days of the Global Sprint 2016. I think that the best approach is to end my participation for this year with my project. Anyway I would like to share some preview of recent developments made with Grafoscopio: [Panama Papers: a case for reproducible research, data activism and frictionless data](http://mutabit.com/offray/blog/es/entry/panama-papers-1)

Cheers,

Offray

Ps: So how can I disable further notifications to my mail about Global Sprint 2016?

**Comment by acabunoc** [comment]
Hi @offray -

I'm so sorry you won't be able to join us! Thanks for letting us know, and for the update on your project (exciting!).

I'll close the issue for you. You can 'unwatch' the repository to stop notifications:

![screen shot 2016-05-16 at 08 02 59](https://cloud.githubusercontent.com/assets/617994/15288951/a903472c-1b3c-11e6-8893-cdccf75570bd.png)

**Comment by offray** [comment]
Thanks. May be next year. In the meantime I will be in contact with 
Mozilla Science initiatives via twitter.

Cheers,

Offray
