### ISSUE TITLE
Open Access for the Global South

### ISSUE THREAD

**Issue by acabunoc** [mozillascience/global-sprint-2016#40]
**[ Project Lead ]** Jo
**[ GitHub Repo ]** 
**[ Track ]** Open Educational Resource: you're collaborating on curriculum or other educational resources
**[ Level ]** Beginner
**[ Timezone ]**

### Description

***
## Want to Contribute?
Join us at the [Global Sprint June 2-3](https://www.mozillascience.org/global-sprint-2016). Leave a comment in this issue to let the project lead know you're interested in contributing during #mozsprint 2016!
***

## Note to the Project Lead
Congrats, Jo! This is your official project listing for the [Mozilla Science Global Sprint 2016](https://www.mozillascience.org/global-sprint-2016). To confirm your submission, please complete the following:

- [ ] Provide a GitHub repository for work and discussion on your project
- [ ] Confirm in a comment that at least one person will be available to review and answer questions on this project from 9-5 in their timezone on both June 2 & 3.

#### Do you want to become a featured project? :tada:
Here are some exercises that will help your project be more inviting to new contributors. We hope you'll try to complete some of these as you prepare for #mozsprint.

If you complete *all* the exercises, your project will be eligible to be featured in our [collection of open source science projects](https://mozillascience.org/collaborate)! Once you've finished this list, contact @acabunoc to submit your project for review.

* [ ] [README.md](http://mozillascience.github.io/working-open-workshop/writing_readme/):
* [ ] [LICENSE](http://choosealicense.com/):
* [ ] [CONTRIBUTING.md](http://mozillascience.github.io/working-open-workshop/contributing/):
* [ ] [Roadmap or an Issue Tracker (with tasks to complete)](http://mozillascience.github.io/working-open-workshop/roadmapping/):
* [ ] [Data Reuse Plan](http://mozillascience.github.io/working-open-workshop/data_reuse/) (if applicable):
* [ ] [Code of Conduct](http://mozillascience.github.io/working-open-workshop/code_of_conduct/):
* [ ] [Personas](http://mozillascience.github.io/working-open-workshop/personas_pathways/):

**Comment by jibe-b** [comment]
Hi there! Your project sound good, I advertized to the SOHA project (Open Science in Haiti and French speaking Africa). I hope there can be synergies, making use of what has already been done in the passed months, years and decades.

Best regards,

**Comment by brucellino** [comment]
the title of this project is interesting. We may be able to bring some resources to bare with the [Sci-GaIA](http://www.sci-gaia.eu) project, in particular via the [Open Science Platform](http://www.sci-gaia.eu/osp). Looking forward to details.

**Comment by johav** [comment]
Hi there, I suggested this project since I would love to see discussions going on and about. Sadly, it looks as if I won't be able to participate fulltime on June 2/3. Anyone else interested in being the lead for this??? I would be happy in helping to build the repository.

**Comment by acabunoc** [comment]
Does someone want to lead this project during #mozsprint? Comment here to let me know!

If I hear nothing before the event starts, I'll close this. Thanks for submitting @johav :)
