### ISSUE TITLE
Add project submission & host submission forms to landing page

### ISSUE THREAD

**Issue by acabunoc** [mozillascience/global-sprint-2016#5]
We need to add info for submitting projects & sites to the landing page.

page: https://www.mozillascience.org/global-sprint-2016
template to update: https://github.com/mozillascience/site/blob/master/views/events/globalsprint2016.jade

owner: @acabunoc
accountable: @acabunoc or @auremoser 

@auremoser - let me know if you want to work on this / have time. NOTE: this is *not* currently assigned to you. Please assign it to yourself when you start working on this. I'll do the same.

**Comment by auremoser** [comment]
Ok, thanks @acabunoc, I'll work on it and ask if I have questions!

**Comment by auremoser** [comment]
Done, just committed on https://github.com/mozillascience/site/commit/4dd895c8c4d863dbc7dddeb22b14c9c52493be35

Looks like this, nothing fancy, but functional: 
![site](https://cloud.githubusercontent.com/assets/1559703/14088438/6b6a6a72-f4e4-11e5-8794-8eff47d78b07.png)

**Comment by acabunoc** [comment]
Woo, thanks so much @auremoser! 

Couple things left:
- [ ] some small tweaks on copy
  * bring in more from [@arlissc's blog post](https://mozillascience.org/global-sprint-2016-site-and-project-applications-open), specifically the 'projects must' section before they apply
- [ ] push this to our live site - @acabunoc can do this (assign issue to me when we're ready for this!)

I can take a look at both tomorrow! Un-assigned again in the meantime.

**Comment by auremoser** [comment]
I didn't realize you had setup staging, feel free to push the changes whenever you're ready, I added the bullet details and linked to the blog post: 
![site](https://cloud.githubusercontent.com/assets/1559703/14091194/ae214ebc-f4f3-11e5-8534-5516ac521bed.png)

**Comment by acabunoc** [comment]
Nice! Thanks!

I'll push to production once [this](https://github.com/mozillascience/site/commit/4dd895c8c4d863dbc7dddeb22b14c9c52493be35#commitcomment-16878236) is cleared up

**Comment by auremoser** [comment]
O.k. done, feel free to close when you're ready to merge.

**Comment by acabunoc** [comment]
It's live :) closing :+1: :heart:
