### ISSUE TITLE
What can X do to encourage Open Science?

### ISSUE THREAD

**Issue by Daniel-Mietchen** [mozillascience/global-sprint-2016#52]
Let X be a stakeholder in research - be it a researcher, a research institution, a research funder, a research library, a scholarly journal, a research database, a repo of research-relevant code, a citizen science project, a student, you name it.

My question, then, is what X can do to encourage Open Science, i.e.
* what actions they can take themselves to experiment with open approaches to sharing research
* what actions they can take to signal to encourage others to engage with Open Science.

In part inspired by #36, I have started a number of [threads](https://openscience.ub.uni-bielefeld.de/tag/stakeholders) for different X, e.g. [What can research institutions do to encourage open science?](https://openscience.ub.uni-bielefeld.de/882/what-can-research-institutions-do-to-encourage-open-science), and I plan to devote some of my time at the Global Sprint to moving that conversation forward.

Your input would be most welcome.

**Comment by acabunoc** [comment]
Hey! I'm going to reconcile this with #53 :) THanks @Daniel-Mietchen!
